name: Build Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: '9477386' # Latest as of 2025

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Build the release APK
      - name: Build release APK
        run: ./gradlew assembleRelease

      # Decode and set up keystore for signing (if secrets are provided)
      - name: Decode Keystore
        if: ${{ env.SIGNING_KEYSTORE_BASE64 != '' }}
        env:
          SIGNING_KEYSTORE_BASE64: ${{ secrets.SIGNING_KEYSTORE_BASE64 }}
        run: |
          echo $SIGNING_KEYSTORE_BASE64 | base64 -d > my-release-key.jks
          echo "storeFile=my-release-key.jks" >> ./app/signing.properties
          echo "storePassword=${{ secrets.SIGNING_KEYSTORE_PASSWORD }}" >> ./app/signing.properties
          echo "keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}" >> ./app/signing.properties
          echo "keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" >> ./app/signing.properties

      # Sign the APK (if keystore is set up)
      - name: Sign APK
        if: ${{ env.SIGNING_KEYSTORE_BASE64 != '' }}
        run: |
          jarsigner -keystore my-release-key.jks -storepass ${{ secrets.SIGNING_KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.SIGNING_KEY_PASSWORD }} \
            app/build/outputs/apk/release/app-release-unsigned.apk ${{ secrets.SIGNING_KEY_ALIAS }}
          zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release.apk

      # Upload the APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error
